# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='cli2gui',
    version='2020.7.1',
    description='Use this module to convert a cli program to a gui',
    python_requires='==3.*,>=3.5.0',
    project_urls={
        "documentation":
            "https://github.com/FHPythonUtils/Cli2Gui/blob/master/README.md",
        "homepage":
            "https://github.com/FHPythonUtils/Cli2Gui",
        "repository":
            "https://github.com/FHPythonUtils/Cli2Gui"
    },
    author='FredHappyface',
    classifiers=[
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Operating System :: OS Independent'
    ],
    packages=['Cli2Gui', 'Cli2Gui.application', 'Cli2Gui.tojson'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'art==4.*,>=4.6.0', 'emoji==0.*,>=0.5.4',
        'getostheme==2020.*,>=2020.2.0', 'pillow==7.*,>=7.1.1',
        'pypandoc==1.*,>=1.5.0', 'pysimplegui==4.*,>=4.18.2',
        'pyyaml==5.*,>=5.3.1'
    ],
)
